CREATE SCHEMA `xeno_canto` DEFAULT CHARACTER SET utf8;
USE `xeno_canto`;
CREATE TABLE `main` (
  `ClassName` varchar(45) CHARACTER SET latin1 COLLATE latin1_german1_ci DEFAULT NULL,
  `XenoCantoId` int unsigned DEFAULT NULL,
  `SoundType` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `Quality` tinyint DEFAULT NULL,
  `Duration` DECIMAL(11, 6) DEFAULT NULL,
  `Country` varchar(45) CHARACTER SET latin1 DEFAULT NULL,
  `Locality` text CHARACTER SET utf8,
  `Latitude` DECIMAL(11, 6) DEFAULT NULL,
  `Longitude` DECIMAL(11, 6) DEFAULT NULL,
  `Elevation` DECIMAL(11, 6) DEFAULT NULL,
  `Recordist` text CHARACTER SET utf8,
  `Date` date DEFAULT NULL,
  `Time` time DEFAULT NULL,
  `Genus` varchar(45) CHARACTER SET latin1 DEFAULT NULL,
  `Species` varchar(45) CHARACTER SET latin1 DEFAULT NULL,
  `SubSpecies` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `EnglishName` varchar(45) CHARACTER SET latin1 DEFAULT NULL,
  `OriginalFileName` text CHARACTER SET utf8,
  `License` varchar(45) CHARACTER SET latin1 DEFAULT NULL,
  `BirdSeen` tinyint unsigned DEFAULT NULL,
  `PlaybackUsed` tinyint unsigned DEFAULT NULL,
  `SampleRate` int unsigned DEFAULT NULL,
  `BitRate` int unsigned DEFAULT NULL,
  `Channels` tinyint unsigned DEFAULT NULL,
  `FileSize` int unsigned DEFAULT NULL,
  `BackgroundSpecies` varchar(1024) CHARACTER SET latin1 DEFAULT NULL,
  `Remarks` text CHARACTER SET utf8,
  `Created` datetime DEFAULT NULL,
  `Modified` datetime DEFAULT NULL,
  `WebState` tinyint unsigned DEFAULT '1',
  `DbId` int unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`DbId`),
  UNIQUE KEY `DbId_UNIQUE` (`DbId`),
  UNIQUE KEY `XenoCantoId_UNIQUE` (`XenoCantoId`)
) ENGINE = InnoDB AUTO_INCREMENT = 107780 DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;